# <font color="purple"> **1.9 Librerías fundamentales: Pandas** </font>

`Pandas` (<https://pandas.pydata.org/>) es una poderosa biblioteca de Python utilizada principalmente para la manipulación y análisis de datos en el ámbito de la ciencia de datos. Su funcionalidad y utilidad radican en su capacidad para trabajar con conjuntos de datos tabulares de manera eficiente y flexible. 

<img src="panda.png" width="350" style="margin-left: 300px;">


Algunas de las características de Pandas incluyen:

- **Estructuras de Datos Flexibles**: Pandas proporciona dos estructuras de datos principales: **Series y DataFrame**. Una *Serie es una matriz unidimensional que puede contener datos de cualquier tipo*, mientras que un *DataFrame es una estructura bidimensional similar a una tabla* que organiza los datos en filas y columnas, lo que permite la manipulación de datos tabulares de manera intuitiva.

- **Manipulación de Datos**: Pandas ofrece una amplia gama de funcionalidades para la manipulación de datos, incluyendo la selección, filtrado, agregación, transformación y visualización de datos. Estas operaciones permiten limpiar y preparar los datos para su análisis de manera eficiente.

- **Integración con otras bibliotecas**: Pandas se integra perfectamente con otras bibliotecas populares de Python utilizadas en ciencia de datos, como NumPy, Matplotlib y Scikit-learn, lo que permite un flujo de trabajo completo para el análisis y modelado de datos.

Con Pandas, los científicos de la Tierra pueden cargar, limpiar y analizar conjuntos de datos complejos, realizar cálculos estadísticos y crear visualizaciones informativas que ayuden a comprender mejor los fenómenos naturales y los procesos terrestres.

Para saber más de pandas, revisar: <https://aprendepython.es/third-party/data-science/pandas/>

Para comenzar a usar Pandas, la forma estándar es importando la librería de la siguiente manera:

```python
import pandas as pd

In [3]:
#Importamos pandas y otras librerías útiles para el notebook
import pandas as pd
import numpy as np

# <font color="brown"> **Series** </font>

Podríamos pensar en una *serie* como un array unidimensional que puede almacenar datos de cualquier tipo (<https://www.geeksforgeeks.org/pandas/python-pandas-series/>). Además, cada valor tiene asignado una etiqueta (índice) y además admite un título (nombre). Es similar a una columna en una hoja de Excel o en una tabla de bases de datos.

**Características clave de las series:**

- Soporta indexación basada en enteros y etiquetas.
- Almacena tipos de datos heterogéneos.
- Ofrece una variedad de métodos integrados para la manipulación y análisis de datos.

### <font color="darkblue"> **¿Cómo se crea un serie?**</font>
Una serie puede crearse a partir de diferentes estructuras de datos como listas, arrays NumPy, diccionarios o valores escalares.

In [45]:
#Vamos a crear una serie

data=[1,2,3,4]

serie_numeros=pd.Series(data)
print(serie_numeros)

0    1
1    2
2    3
3    4
dtype: int64

Los números de la izquierda (0, 1, 2, 3) representan el índice. Los valores (10, 20, 30, 40) representan los datos almacenados en la serie.

In [43]:
#Una serie a partir de un array
arreglo=np.array([1,2,3,4])
serie_arreglo=pd.Series(arreglo)
serie_arreglo

0    1
1    2
2    3
3    4
dtype: int64

In [4]:
tupla=(12,43)
serie_tupla=pd.Series(tupla)
serie_tupla

0    12
1    43
dtype: int64

In [5]:
#Una serie a partir de un diccionario
diccionario={"nombre":[12,3,4]}
serie_dict=pd.Series(diccionario)
serie_dict

nombre    [12, 3, 4]
dtype: object

### <font color="darkblue"> **Acceso a elementos de la Serie**</font>

En Pandas podemos acceder a elementos de series de dos maneras:

- **Indexación basada en posiciones**: Asigna posiciones numéricas similares a las listas en Python.
- **Indexación basada en etiquetas**: Asigna etiquetas de índice personalizadas a los elementos.

In [6]:
#Identación basada en posiciones

letters = np.array(['g','e','e','k','s','f', 'o','r','g','e','e','k','s'])
serie_letras = pd.Series(letters)

print(serie_letras[:5])

0    g
1    e
2    e
3    k
4    s
dtype: object

In [7]:
#Identación basada en etiquetas

#retomamos el arreglo letters
letters

#Asigamos las etiquetas
serie_etiquetas = pd.Series(letters,index=["a",11,12,13,14,15,16,17,18,19,20,21,22])

print(serie_etiquetas[11])

e

# <font color="brown"> **DataFrame** </font>

El objeto principal de pandas es un `DataFrame`. Un DataFrame en Pandas es una estructura de datos bidimensional etiquetada y tabular que se utiliza para almacenar y manipular conjuntos de datos de forma similar a una hoja de cálculo o una tabla de base de datos. Esencialmente, un DataFrame consta de **filas y columnas**, donde cada columna puede contener datos de diferentes tipos, como enteros, flotantes, cadenas de caracteres u otros objetos de Python. Proporciona una manera poderosa y flexible de organizar, analizar y manipular datos tabulares.

#### <font color="orange"> **Ejemplo 1: Mi primer DataFrame** </font>

Un `DataFrame` se crea a partir de un diccionario. Para convertir el diccionario a DataFrame se ocupa la función `.DataFrame()`.

In [8]:
dic={"Alumnos":["Meli","Cinty","Hannia","joseph","kenay","Ana","Raul","Ricardo","Carla","Angel","Sara"],
    "Edad":[22,23,24,24,23,22,24,23,22,23,np.nan]} #np.nan
df=pd.DataFrame(dic)
df

    Alumnos  Edad
0      Meli  22.0
1     Cinty  23.0
2    Hannia  24.0
3    joseph  24.0
4     kenay  23.0
5       Ana  22.0
6      Raul  24.0
7   Ricardo  23.0
8     Carla  22.0
9     Angel  23.0
10     Sara   NaN

### <font color="darkblue"> **Explorando los datos** </font>

Los DataFrames cuentan con funciones y atributos que nos permiten conocer y explorar, de forma resumida, los datos contenidos en dichos DataFrames: 

* `.info()`: Nos muestra un resumen general de los datos.
* `.shape`: Forma de los datos (filas,columnas)
* `.describe()`: Muestra estadísticos básicos de los datos
* `.columns`: Muestra los nombres de las columnas
* `.head()`: Muestra las primeras 5 filas
* `.tail()`: Muestra las últimas 5 filas

Para hacer uso de las funciones y atributos asociados a un DataFrame, es necesario colocar el nombre del DataFrame al que queremos aplicar estas herramientas. Por ejemplo: `df.info()`.

In [9]:
#Vamos a hacer uso de los atributos y funciones
#Retomamos el DataFrame creado anteriormente
#df
print("Información")
print(df.info())
print("*************")

print("Forma")
print(df.shape)
print("*************")

print("Estadísticos básicos")
print(df.describe())

Información
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11 entries, 0 to 10
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Alumnos  11 non-null     object
 1   Edad     10 non-null     float64
dtypes: float64(1), object(1)
memory usage: 308.0+ bytes
None
*************
Forma
(11, 2)
*************
Estadísticos básicos
            Edad
count  10.000000
mean   23.000000
std     0.816497
min    22.000000
25%    22.250000
50%    23.000000
75%    23.750000
max    24.000000

In [10]:
df.describe().iloc[2]

Edad    0.816497
Name: std, dtype: float64

In [11]:
print("Columnas")
print(df.columns)
print("*************")

print("Primeras 5 filas")
print(df.head())
print("*************")

print("Últimas 5 filas")
print(df.tail())

Columnas
Index(['Alumnos', 'Edad'], dtype='object')
*************
Primeras 5 filas
  Alumnos  Edad
0    Meli  22.0
1   Cinty  23.0
2  Hannia  24.0
3  joseph  24.0
4   kenay  23.0
*************
Últimas 5 filas
    Alumnos  Edad
6      Raul  24.0
7   Ricardo  23.0
8     Carla  22.0
9     Angel  23.0
10     Sara   NaN

In [12]:
#¿Y si justo me interesa observar las primeras 6 filas?
df.tail(6)

    Alumnos  Edad
5       Ana  22.0
6      Raul  24.0
7   Ricardo  23.0
8     Carla  22.0
9     Angel  23.0
10     Sara   NaN

### <font color="darkblue"> **Selección de datos** </font>

En Pandas podemos seleccionar datos de dos maneras diferentes: **por una o más columnas** ó **por condiciones**.

In [13]:
#Creo un nuevo DataFrame

datos = {
    "Dias": np.arange(1, 11, 1) , #Cada columna debe de tener la misma cantidad de elementos
    "Temperatura_°C": np.random.uniform(18, 35, 10), #La cantidad de keys será la cantidad de columnas de mi dataframe
    "Humedad_%": np.random.uniform(40, 90, 10),
    "PM2.5_µg/m3": np.random.uniform(5, 60, 10),
    "Ozono_ppb": np.random.uniform(10, 80, 10),
    "Velocidad_Viento_m/s": np.random.uniform(0.5, 6, 10)
}

df_mediciones = pd.DataFrame(datos)

df_mediciones

,Dias,Temperatura_°C,Humedad_%,PM2.5_µg/m3,Ozono_ppb,Velocidad_Viento_m/s
0,1,25.983123,54.993950,29.668013,57.974522,1.850943
1,2,20.129446,74.763329,32.512082,72.208673,5.225846
2,3,25.085027,66.661498,47.619934,65.480722,1.696487
3,4,32.866821,73.312064,38.564084,62.938390,5.688308
4,5,18.762157,51.690538,50.940997,25.674806,1.194344
5,6,29.495208,50.640093,43.482372,57.178985,2.124170
6,7,30.160526,43.004258,5.052521,74.625000,3.592655
7,8,22.244517,74.456034,42.191956,66.900413,2.731100
8,9,24.273794,70.949504,37.712909,57.560337,1.012552
9,10,30.602216,69.466922,52.243519,49.430318,1.575129

#### <font color="orange"> **Ejemplo 1: Seleccionando una columna**

In [14]:
#Quiero elegir la columna de Ozono_ppb
df_mediciones["Ozono_ppb"]

0    57.974522
1    72.208673
2    65.480722
3    62.938390
4    25.674806
5    57.178985
6    74.625000
7    66.900413
8    57.560337
9    49.430318
Name: Ozono_ppb, dtype: float64

In [46]:
#¿Se podrá seleccionar por índices?
df_mediciones[0]

KeyError: 0

In [50]:
#Otra manera de seleccionar una columna
df_mediciones.iloc[:,2] #[filas, columnas]

0    54.993950
1    74.763329
2    66.661498
3    73.312064
4    51.690538
5    50.640093
6    43.004258
7    74.456034
8    70.949504
9    69.466922
Name: Humedad_%, dtype: float64

In [38]:
df_mediciones["Ozono_ppb"].dtype

dtype('float64')

In [51]:
df_mediciones

,Dias,Temperatura_°C,Humedad_%,PM2.5_µg/m3,Ozono_ppb,Velocidad_Viento_m/s
0,1,25.983123,54.993950,29.668013,57.974522,1.850943
1,2,20.129446,74.763329,32.512082,72.208673,5.225846
2,3,25.085027,66.661498,47.619934,65.480722,1.696487
3,4,32.866821,73.312064,38.564084,62.938390,5.688308
4,5,18.762157,51.690538,50.940997,25.674806,1.194344
5,6,29.495208,50.640093,43.482372,57.178985,2.124170
6,7,30.160526,43.004258,5.052521,74.625000,3.592655
7,8,22.244517,74.456034,42.191956,66.900413,2.731100
8,9,24.273794,70.949504,37.712909,57.560337,1.012552
9,10,30.602216,69.466922,52.243519,49.430318,1.575129

In [53]:
df_mediciones.Ozono_ppb.values

array([57.97452245, 72.20867267, 65.48072237, 62.93838998, 25.67480587,
       57.17898482, 74.62499984, 66.90041261, 57.56033707, 49.43031801])

In [54]:
df_mediciones.loc[df_mediciones["Ozono_ppb"]== 25.674806]

Empty DataFrame
Columns: [Dias, Temperatura_°C, Humedad_%, PM2.5_µg/m3, Ozono_ppb, Velocidad_Viento_m/s]
Index: []

In [55]:
df_mediciones.loc[df_mediciones["Ozono_ppb"]== df_mediciones.Ozono_ppb.values[4]]

,Dias,Temperatura_°C,Humedad_%,PM2.5_µg/m3,Ozono_ppb,Velocidad_Viento_m/s
4,5,18.762157,51.690538,50.940997,25.674806,1.194344

In [16]:
df_mediciones.Ozono_ppb

0    57.974522
1    72.208673
2    65.480722
3    62.938390
4    25.674806
5    57.178985
6    74.625000
7    66.900413
8    57.560337
9    49.430318
Name: Ozono_ppb, dtype: float64

In [17]:
df_mediciones.PM2.5_µg/m3

SyntaxError: invalid decimal literal (2890734883.py, line 1)

#### <font color="orange"> **Ejemplo 2: Seleccionando más de una columna**

In [42]:
#Quiero seleccionar Humedad y Velocidad del viento
df_mediciones[["Humedad_%","Temperatura_°C"]]

   Humedad_%  Temperatura_°C
0  56.731588       32.813752
1  82.919389       26.963592
2  70.846621       27.003248
3  53.101372       25.770247
4  59.662024       18.681034
5  42.507068       27.986638
6  46.326238       32.176351
7  42.908156       28.936499
8  62.790280       26.874087
9  45.518907       23.295132

#### <font color="orange"> **Ejemplo 3: Filtrando por condiciones**

In [45]:
#Quiero filtrar todos datos de PM2.5 que sean menores de 20 ug/m3

df_mediciones[df_mediciones["PM2.5_µg/m3"]<20]#["PM2.5_µg/m3"]#Como podrán observar el filtrar por condiciones no sólo me arroja el valor de la columna
                                               #que cumple con la condición, sino también toda la fila

,Dias,Temperatura_°C,Humedad_%,PM2.5_µg/m3,Ozono_ppb,Velocidad_Viento_m/s
0,1,32.813752,56.731588,11.147792,24.067244,4.222077
8,9,26.874087,62.790280,8.402167,38.160095,0.529275
9,10,23.295132,45.518907,16.813747,11.714927,2.600520

#### <font color="orange"> **Ejemplo 4: Filtrando por múltiples condiciones** </font>

Anteriormente hemos visto que para evaluar condiciones múltiples podíamos hacer uso de los operadores `and` y `or`. Sin embargo, en Pandas la sintaxis cambia:
* `and` =>`&` 
* `or` => `|`

In [50]:
#Puedo filtrar con tantas condiciones yo quiera
df_mediciones[(df_mediciones["PM2.5_µg/m3"]<20) | (df_mediciones["Humedad_%"]>50)]

,Dias,Temperatura_°C,Humedad_%,PM2.5_µg/m3,Ozono_ppb,Velocidad_Viento_m/s
0,1,20.905312,52.164638,42.465903,17.369752,2.831092
1,2,34.260870,88.214268,14.129935,75.026860,0.953467
2,3,33.582347,89.247061,24.587228,30.115135,2.605188
3,4,28.278423,73.528212,37.808525,20.268231,1.083560
4,5,26.172771,77.084413,34.710753,41.904900,0.934854
5,6,30.028333,69.913591,50.681984,29.686111,3.406867
7,8,25.322219,63.372411,6.978326,51.539900,2.633717
8,9,24.068004,82.993864,27.009107,31.670783,2.971741
9,10,29.659190,59.068082,23.221323,14.284556,4.954029

Como vimos, la forma en la que están definidos los nombres de las columnas en `df_mediciones` no es tan amigable a la hora de seleccionar datos. Entonces, ¿Solo nos queda conformarnos y seguir trabajando con ellos? 

¡AFORTUNADAMENTE NO!, los DataFrames cuentan con otra función que permite renombrar los nombres de las columnas `.rename()`.

In [56]:
df_mediciones2 = df_mediciones.rename(columns={
    "Temperatura_°C": "Temp",
    "Humedad_%": "HR",
    "PM2.5_µg/m3": "PM25",
    "Ozono_ppb": "Ozono",
    "Velocidad_Viento_m/s":"Velocidad_Viento"
})

df_mediciones2

   Dias       Temp         HR       PM25      Ozono  Velocidad_Viento
0     1  25.983123  54.993950  29.668013  57.974522          1.850943
1     2  20.129446  74.763329  32.512082  72.208673          5.225846
2     3  25.085027  66.661498  47.619934  65.480722          1.696487
3     4  32.866821  73.312064  38.564084  62.938390          5.688308
4     5  18.762157  51.690538  50.940997  25.674806          1.194344
5     6  29.495208  50.640093  43.482372  57.178985          2.124170
6     7  30.160526  43.004258   5.052521  74.625000          3.592655
7     8  22.244517  74.456034  42.191956  66.900413          2.731100
8     9  24.273794  70.949504  37.712909  57.560337          1.012552
9    10  30.602216  69.466922  52.243519  49.430318          1.575129

### <font color="darkblue"> **Operando DataFrames** </font>

Las operaciones con columnas y filas en Pandas son muy comunes y útiles para calcular estadísticas o realizar operaciones matemáticas.

* Operaciones estadísticas
    * `.mean()`
    * `.sum()`
    * `.max()`
    * `.min()`
    * `.std()`
    * `.median()`


* Operaciones matemáticas
`+`, `-`, `%`, `*`, .....

#### <font color="orange">**Ejemplo 1: Operaciones estadísticas**

In [54]:
#Retomamos los datos de df_mediciones2
print(df_mediciones2.mean())  #Nos saca el promedio en cada una de las columnas

Dias                 5.500000
Temp                27.563153
HR                  69.927523
PM25                32.016771
Ozono               34.949319
Velocidad_Viento     2.637821
dtype: float64

In [58]:
df

    Alumnos  Edad
0      Meli  22.0
1     Cinty  23.0
2    Hannia  24.0
3    joseph  24.0
4     kenay  23.0
5       Ana  22.0
6      Raul  24.0
7   Ricardo  23.0
8     Carla  22.0
9     Angel  23.0
10     Sara   NaN

In [55]:
#Ejemplo 2: Retomando el primer DataFrame que creamos
df.mean()

TypeError: Could not convert ['MeliCintyHanniajosephkenayAnaRaulRicardoCarlaAngelSara'] to numeric

In [59]:
#¿Si solo quiero el promedio de una columna?
df["Edad"].mean()

np.float64(23.0)

#### <font color="orange">**Ejemplo 2: Operaciones matemáticas**

In [57]:
asistencia_clase={"dia_1":[50,10,1,20,30,15,18],
                    "dia_2":[2,8,10,9,0,14,1],
                    "dia_3":[0,0,10,25,33,28,13]}

df_asistencia_clase=pd.DataFrame(asistencia_clase)
df_asistencia_clase

   dia_1  dia_2  dia_3
0     50      2      0
1     10      8      0
2      1     10     10
3     20      9     25
4     30      0     33
5     15     14     28
6     18      1     13

In [58]:
#¿Qué creen que me regrese esta operación?
df_asistencia_clase["dia_1"]+df_asistencia_clase["dia_2"]+df_asistencia_clase["dia_3"]

0    52
1    18
2    21
3    54
4    63
5    57
6    32
dtype: int64

Ahora quiero agregar una nueva columna que contenga el resultado de la operación anterior. <font color="brown">OJO: Solo podemos agregar columnas siempre y cuando el número de filas de la nueva columna sea el mismo que las del DataFrame al que queremos agregar la columna.

In [59]:
df_asistencia_clase["Total"]=df_asistencia_clase["dia_1"]+df_asistencia_clase["dia_2"]+df_asistencia_clase["dia_3"]

In [60]:
df_asistencia_clase

   dia_1  dia_2  dia_3  Total
0     50      2      0     52
1     10      8      0     18
2      1     10     10     21
3     20      9     25     54
4     30      0     33     63
5     15     14     28     57
6     18      1     13     32

Al igual que los arreglos, **los DataFrames son mutable**s. Es decir, podemos hacer cambios en los valores de nuestro DataFrame. Una, de varias maneras de hacer esto, es con el atributo `loc` que se utiliza para hacer cambios específicos en partes. 

`df.loc[condicion,columna]=nuevo_valor`

In [63]:
#Retomando el primer dataframe
df

    Alumnos  Edad
0      Meli  22.0
1     Cinty  23.0
2    Hannia  24.0
3    joseph  24.0
4     kenay  23.0
5       Ana  22.0
6      Raul  24.0
7   Ricardo  23.0
8     Carla  22.0
9     Angel  23.0
10     Sara   NaN

In [68]:
df.loc[df["Alumnos"]=="Carla","Edad"]=23

In [67]:
df

    Alumnos  Edad
0      Meli  22.0
1     Cinty  23.0
2    Hannia  24.0
3    joseph  24.0
4     kenay  23.0
5       Ana  22.0
6      Raul  24.0
7   Ricardo  23.0
8     Carla  24.0
9     Angel  23.0
10     Sara   NaN

In [73]:
df.loc[df["Alumnos"]==df.iloc[9,0],"Alumnos"]="Leonardo"

In [71]:
df.iloc[9]

Alumnos    Leonardo
Edad           23.0
Name: 9, dtype: object

## <font color="darkblue"> **Agrupando ando** </font>

En pandas, agrupar datos significa dividir el DataFrame en subconjuntos según una categoría y aplicar una operación a cada grupo. La función para dividr un DataFrame en subconjuntos es `pd.groupby()`.

#### <font color="orange"> **Ejemplo 1: Agrupando y operando** </font>

Veremos dos maneras diferentes de agrupar:

* La primera utiliza la sintaxis de `df.groupby` y un `.agg` dentro de agg tenemos que señalar primero la columna y luego la operación que queremos hacer. O sea `.agg({"columna:operacion"})`. 

* Otra manera, un poco más directa es hacer `df.groupby(categoria).mean()[columna]`. Es decir, primero con groupby agrupamos los datos por esa categoría y luego sacamos el promedio de la columna que definamos.

In [74]:
#Retomando df_mediciones2
df_3=df_mediciones2[["Temp","HR","PM25","Ozono","Velocidad_Viento"]]

#Agregando una nueva columna al dataframe

df_3["Meses"]=["Ene","Feb","Mar","Ene","Feb","Mar","Ene","Feb","Mar","Ene"]

In [75]:
df_3

        Temp         HR       PM25      Ozono  Velocidad_Viento Meses
0  25.983123  54.993950  29.668013  57.974522          1.850943   Ene
1  20.129446  74.763329  32.512082  72.208673          5.225846   Feb
2  25.085027  66.661498  47.619934  65.480722          1.696487   Mar
3  32.866821  73.312064  38.564084  62.938390          5.688308   Ene
4  18.762157  51.690538  50.940997  25.674806          1.194344   Feb
5  29.495208  50.640093  43.482372  57.178985          2.124170   Mar
6  30.160526  43.004258   5.052521  74.625000          3.592655   Ene
7  22.244517  74.456034  42.191956  66.900413          2.731100   Feb
8  24.273794  70.949504  37.712909  57.560337          1.012552   Mar
9  30.602216  69.466922  52.243519  49.430318          1.575129   Ene

In [77]:
#Con .agg

#Quiero agrupar por mes y que me saque le promedio de la Temperatura
data_mensual=df_3.groupby("Meses").agg({"Temp":"mean"}) 

#¿Notaron algo diferente?

In [79]:
data_mensual.reset_index()

  Meses       Temp
0   Ene  29.903171
1   Feb  20.378707
2   Mar  26.284676

In [82]:
#Segunda manera
df_bv=df_3.groupby("Meses").mean()["Temp"]

In [83]:
df_bv

Meses
Ene    29.903171
Feb    20.378707
Mar    26.284676
Name: Temp, dtype: float64

In [81]:
#Si yo nadamás aplico .groupby()

df_3.groupby("Meses").mean()

            Temp         HR       PM25      Ozono  Velocidad_Viento
Meses
Ene    29.903171  60.194299  31.382034  61.242058          3.176759
Feb    20.378707  66.969967  41.881678  54.927964          3.050430
Mar    26.284676  62.750365  42.938405  60.073348          1.611069

También podemos ordenar nuestros datos de forma asecendente o descendente. Para ello ocupamos la función `.sort_values()`

In [84]:
df_3.sort_values(by="Temp") #El argumento que va en la función nos define en base a qué columna quiero que se ordene

        Temp         HR       PM25      Ozono  Velocidad_Viento Meses
4  18.762157  51.690538  50.940997  25.674806          1.194344   Feb
1  20.129446  74.763329  32.512082  72.208673          5.225846   Feb
7  22.244517  74.456034  42.191956  66.900413          2.731100   Feb
8  24.273794  70.949504  37.712909  57.560337          1.012552   Mar
2  25.085027  66.661498  47.619934  65.480722          1.696487   Mar
0  25.983123  54.993950  29.668013  57.974522          1.850943   Ene
5  29.495208  50.640093  43.482372  57.178985          2.124170   Mar
6  30.160526  43.004258   5.052521  74.625000          3.592655   Ene
9  30.602216  69.466922  52.243519  49.430318          1.575129   Ene
3  32.866821  73.312064  38.564084  62.938390          5.688308   Ene

In [89]:
#ascending
df_3.sort_values(by=["Temp"],ascending=False)

        Temp         HR       PM25      Ozono  Velocidad_Viento Meses
3  32.866821  73.312064  38.564084  62.938390          5.688308   Ene
9  30.602216  69.466922  52.243519  49.430318          1.575129   Ene
6  30.160526  43.004258   5.052521  74.625000          3.592655   Ene
5  29.495208  50.640093  43.482372  57.178985          2.124170   Mar
0  25.983123  54.993950  29.668013  57.974522          1.850943   Ene
2  25.085027  66.661498  47.619934  65.480722          1.696487   Mar
8  24.273794  70.949504  37.712909  57.560337          1.012552   Mar
7  22.244517  74.456034  42.191956  66.900413          2.731100   Feb
1  20.129446  74.763329  32.512082  72.208673          5.225846   Feb
4  18.762157  51.690538  50.940997  25.674806          1.194344   Feb

----

### <font color="purple"> **Ejercicio 1:** </font>

* Crea un DataFrame de 3 columnas y 15 filas. Eres libre de asociar los datos a lo que gustes.
* Saca el promedio de la columna 2.
* Agrega una nueva columna con datos categóricos (ej.manzanas,peras,uvas, platano, pera, uva).
* Agrupa por categoría y cuenta cuántos elementos hay en cada una. `Hint: Usa la función .count ()`

In [4]:
#Paso1
df_ejercicio=pd.DataFrame({"Day":np.arange(1,16,1),"sea_level":np.random.rand(15),"sea_temperature":np.random.uniform(25,35,15)})

In [5]:
#Paso2
df_ejercicio.sea_level.mean()

np.float64(0.4815314742824138)

In [6]:
#Paso3
df_ejercicio["Time"]=["M","A","N","M","A","N","M","A","N","M","A","N","M","A","N"] #M=morning, A=afternoon, N=night

In [7]:
#Paso 4
df_ejercicio.groupby("Time").count()

      Day  sea_level  sea_temperature
Time
A       5          5                5
M       5          5                5
N       5          5                5

-----

**Pandas tiene muchísimas ventajas. Una de ellas es que se pueden acceder a los datos e índices rápidamente. Para acceder a los índices ocupamos el atributo `.index`.**

In [90]:
df_agrupado=df_3.groupby("Meses").mean()["Temp"]
df_agrupado

Meses
Ene    29.903171
Feb    20.378707
Mar    26.284676
Name: Temp, dtype: float64

In [91]:
df_agrupado.index

Index(['Ene', 'Feb', 'Mar'], dtype='object', name='Meses')

### **<font color="brown">  La importancia del índice </font>**

En la celda anterior utilizamos `df.index`, pero qué es esto del índice. Vamos a verlo con otro dataframe. Uno que podemos imaginar como los datos de un supermercado que ha registrado ciertas compras a diferentes horas del día.

In [100]:
import datetime
# Creamos una lista de fechas
fechas = [datetime.datetime.today() - datetime.timedelta(days=x) for x in range(25)]  #Crea una lista de 25 fechas, empezando desde
                                                                                     # hoy hacia atrás,restando un día cada vez.

# Creamos un diccionario con datos aleatorios
data = {
    'ID': range(1, 26),
    'Nombre': ['Producto ' + str(i) for i in range(1, 26)],
    'Cantidad': np.random.randint(1, 100, size=25),
    'Precio': np.random.uniform(1, 100, size=25),
    'Fecha': fechas
}

# Creamos el DataFrame
df5 = pd.DataFrame(data)

# Mostramos el DataFrame
df5

    ID       Nombre  Cantidad     Precio                      Fecha
0    1   Producto 1        16  86.110440 2026-09-09 21:25:23.478447
1    2   Producto 2        21  41.802614 2026-09-08 21:25:23.478459
2    3   Producto 3        39  64.167494 2026-09-07 21:25:23.478466
3    4   Producto 4        82  40.057213 2026-09-06 21:25:23.478471
4    5   Producto 5        46  94.329607 2026-09-05 21:25:23.478476
5    6   Producto 6        66  49.644055 2026-09-04 21:25:23.478481
6    7   Producto 7        14  24.607874 2026-09-03 21:25:23.478485
7    8   Producto 8        36  15.247539 2026-09-02 21:25:23.478492
8    9   Producto 9        68  78.957131 2026-09-01 21:25:23.478498
9   10  Producto 10        19  30.833318 2026-08-31 21:25:23.478503
10  11  Producto 11        39  53.703745 2026-08-30 21:25:23.478508
11  12  Producto 12        45  87.184329 2026-08-29 21:25:23.478513
12  13  Producto 13        77  50.361816 2026-08-28 21:25:23.478518
13  14  Producto 14        50  77.111149 2026-08-27 21:25:23.478522
14  15  Producto 15        18  57.440966 2026-08-26 21:25:23.478527
15  16  Producto 16        44  43.993422 2026-08-25 21:25:23.478531
16  17  Producto 17        95  16.065666 2026-08-24 21:25:23.478536
17  18  Producto 18        47  93.292640 2026-08-23 21:25:23.478541
18  19  Producto 19        75  26.886551 2026-08-22 21:25:23.478546
19  20  Producto 20        21  68.914678 2026-08-21 21:25:23.478550
20  21  Producto 21        51  44.598222 2026-08-20 21:25:23.478555
21  22  Producto 22         9  13.536628 2026-08-19 21:25:23.478559
22  23  Producto 23        87  18.036258 2026-08-18 21:25:23.478564
23  24  Producto 24        33  71.191052 2026-08-17 21:25:23.478568
24  25  Producto 25        49  64.661246 2026-08-16 21:25:23.478573

El índice en Pandas, `df.index` es una parte fundamental de los DataFrames y Series. Sirve como etiqueta para las filas o elementos de los datos almacenados en estas estructuras de datos. El índice proporciona una identificación única para cada fila y facilita el acceso, la manipulación y la comprensión de los datos almacenados.

Utilidad del índice en Pandas:

1. **Identificación única de filas**: El índice garantiza que cada fila en un DataFrame o Serie tenga una identificación única. Esto permite acceder a filas específicas utilizando etiquetas de índice o realizar operaciones basadas en la ubicación de las filas.

2. **Selección y filtrado de datos**: Pandas permite seleccionar y filtrar datos utilizando etiquetas de índice, lo que facilita la manipulación de conjuntos de datos grandes y complejos. Por ejemplo, puedes seleccionar filas específicas utilizando `df.loc[]` o realizar selecciones basadas en condiciones utilizando operadores de comparación.

3. **Alineación de datos**: Pandas realiza alineación automática de datos basada en el índice durante operaciones aritméticas y de combinación de datos. Esto asegura que las operaciones se realicen correctamente incluso cuando los datos no tienen el mismo orden o las mismas etiquetas de índice.

4. **Operaciones de conjunto**: El índice facilita la realización de operaciones de conjuntos, como la unión, la intersección y la diferencia, entre conjuntos de datos. Esto es especialmente útil al combinar o comparar datos de diferentes fuentes.

5. **Facilita la manipulación de datos temporales**: En el caso de datos temporales, el índice puede representar marcas de tiempo o fechas. Esto permite realizar operaciones de manipulación de series temporales de manera eficiente y realizar análisis basados en el tiempo.

En resumen, el índice en Pandas desempeña un papel crucial en la organización, manipulación y análisis de datos. Proporciona una forma eficiente y poderosa de acceder, filtrar y alinear datos, así como realizar operaciones basadas en etiquetas de fila. Comprender y utilizar el índice de manera efectiva es esencial para trabajar con éxito con conjuntos de datos en Pandas.

Veremos cada uno de estos por partes.

In [101]:
# Funcionalidad 1
print(df5.head())
print("********************************************************************")
# solo el indice
print(df5.head().index)

   ID      Nombre  Cantidad     Precio                      Fecha
0   1  Producto 1        16  86.110440 2026-09-09 21:25:23.478447
1   2  Producto 2        21  41.802614 2026-09-08 21:25:23.478459
2   3  Producto 3        39  64.167494 2026-09-07 21:25:23.478466
3   4  Producto 4        82  40.057213 2026-09-06 21:25:23.478471
4   5  Producto 5        46  94.329607 2026-09-05 21:25:23.478476
********************************************************************
RangeIndex(start=0, stop=5, step=1)

In [102]:
#Funcionalidad 2: Filtrado y selección de datos

# Para ver la primer fila de nuestra base de datos
print(df5.loc[df5.index[0]])

print("*******************************************************")
# Ahora la ultima
print(df5.loc[df5.index[-1]])

print("*******************************************************")
# slice para los primeros 5 elementos del dataframe
print(df5.loc[df5.index<5])

ID                                   1
Nombre                      Producto 1
Cantidad                            16
Precio                        86.11044
Fecha       2026-09-09 21:25:23.478447
Name: 0, dtype: object
*******************************************************
ID                                  25
Nombre                     Producto 25
Cantidad                            49
Precio                       64.661246
Fecha       2026-08-16 21:25:23.478573
Name: 24, dtype: object
*******************************************************
   ID      Nombre  Cantidad     Precio                      Fecha
0   1  Producto 1        16  86.110440 2026-09-09 21:25:23.478447
1   2  Producto 2        21  41.802614 2026-09-08 21:25:23.478459
2   3  Producto 3        39  64.167494 2026-09-07 21:25:23.478466
3   4  Producto 4        82  40.057213 2026-09-06 21:25:23.478471
4   5  Producto 5        46  94.329607 2026-09-05 21:25:23.478476

El índice puede ser modificado una vez que ya se hizo el dataframe. Hay dos maneras de hacer esto. Una es redefiniendo el índice y otra con la función `set_index()` que toma como argumento opcional `inplace=True` para decirle que modifique al objeto `df` directamente sin tener que guardarlo en otra variable. Sin `inplace=True`, no se guardaría nuestro resultado.

In [103]:
#Retomando nuestro df5
# Primera manera
df5.index=df5['Fecha']
df5.head()

,ID,Nombre,Cantidad,Precio,Fecha
Fecha,,,,,
2026-09-09 21:25:23.478447,1,Producto 1,16,86.110440,2026-09-09 21:25:23.478447
2026-09-08 21:25:23.478459,2,Producto 2,21,41.802614,2026-09-08 21:25:23.478459
2026-09-07 21:25:23.478466,3,Producto 3,39,64.167494,2026-09-07 21:25:23.478466
2026-09-06 21:25:23.478471,4,Producto 4,82,40.057213,2026-09-06 21:25:23.478471
2026-09-05 21:25:23.478476,5,Producto 5,46,94.329607,2026-09-05 21:25:23.478476

In [99]:
df5

         Nombre  Cantidad     Precio                      Fecha
ID
1    Producto 1         2  41.849930 2026-09-09 18:19:17.459640
2    Producto 2         6  12.231074 2026-09-08 18:19:17.459654
3    Producto 3        69  89.099773 2026-09-07 18:19:17.459661
4    Producto 4        66  18.736458 2026-09-06 18:19:17.459666
5    Producto 5        98  38.342911 2026-09-05 18:19:17.459671
6    Producto 6        31  63.129633 2026-09-04 18:19:17.459676
7    Producto 7        90  31.540596 2026-09-03 18:19:17.459681
8    Producto 8        33  35.237091 2026-09-02 18:19:17.459688
9    Producto 9        22  59.224043 2026-09-01 18:19:17.459694
10  Producto 10        13   3.469937 2026-08-31 18:19:17.459699
11  Producto 11        71  71.878381 2026-08-30 18:19:17.459705
12  Producto 12        23  26.296869 2026-08-29 18:19:17.459710
13  Producto 13        65  26.837732 2026-08-28 18:19:17.459715
14  Producto 14         5  32.214986 2026-08-27 18:19:17.459719
15  Producto 15        22  77.499653 2026-08-26 18:19:17.459723
16  Producto 16        98  98.483428 2026-08-25 18:19:17.459728
17  Producto 17        58  36.629674 2026-08-24 18:19:17.459733
18  Producto 18        98  43.844185 2026-08-23 18:19:17.459738
19  Producto 19        94  50.628859 2026-08-22 18:19:17.459743
20  Producto 20        97  83.207323 2026-08-21 18:19:17.459747
21  Producto 21        24  95.436436 2026-08-20 18:19:17.459752
22  Producto 22        68  81.604143 2026-08-19 18:19:17.459757
23  Producto 23        97  42.860469 2026-08-18 18:19:17.459761
24  Producto 24        68  67.997864 2026-08-17 18:19:17.459766
25  Producto 25        32  30.921078 2026-08-16 18:19:17.459770

In [105]:
# Segunda manera
df5.set_index('ID',inplace=False)
df5.head()

,ID,Nombre,Cantidad,Precio,Fecha
Fecha,,,,,
2026-09-09 21:25:23.478447,1,Producto 1,16,86.110440,2026-09-09 21:25:23.478447
2026-09-08 21:25:23.478459,2,Producto 2,21,41.802614,2026-09-08 21:25:23.478459
2026-09-07 21:25:23.478466,3,Producto 3,39,64.167494,2026-09-07 21:25:23.478466
2026-09-06 21:25:23.478471,4,Producto 4,82,40.057213,2026-09-06 21:25:23.478471
2026-09-05 21:25:23.478476,5,Producto 5,46,94.329607,2026-09-05 21:25:23.478476

Ahora vamos a hacer otro ejemplo para ver cómo Pandas hace las operaciones con dataframes a partir del índice. Si el índice está bien pensado y escrito en Pandas, podemos hacer muchas cosas. En este caso, vamos a hacer dos nuevos dataframes, uno para la cantidad y otro para el precio de los productos anteriores. Sus valores serán aleatorios. Pero si queremos calcular una operación de dos dataframes diferentes, necesitamos del índice.

In [106]:
#Funcionalidad 3: Alineación de datos

# Suponiendo que df_ventas contiene los datos de ventas y df_productos contiene los precios de los productos
df_ventas = pd.DataFrame({
    'ID': range(1, 26),
    'Cantidad': np.random.randint(1, 100, size=25)
})

df_precios = pd.DataFrame({
    'ID': range(1, 26),
    'Precio': np.random.uniform(1, 100, size=25)
})

print('Ventas')
print(df_ventas.head())
print("***************************")
print('Precio')
print(df_precios.head())
print("***************************")

# Establecemos el índice en ambos DataFrames
df_ventas.set_index('ID', inplace=True)
df_precios.set_index('ID', inplace=True)

# Calculamos el total de ventas multiplicando la cantidad vendida por el precio unitario
print("Total ventas")
total_ventas = df_ventas['Cantidad'] * df_precios['Precio']

# Mostramos el resultado

total_ventas.head()

Ventas
   ID  Cantidad
0   1        75
1   2        73
2   3        24
3   4        54
4   5        40
***************************
Precio
   ID     Precio
0   1  25.205015
1   2  82.690900
2   3   1.228061
3   4  25.953938
4   5  59.056260
***************************
Total ventas

ID
1    1890.376104
2    6036.435686
3      29.473460
4    1401.512678
5    2362.250403
dtype: float64

La cuarta funcionalidad se refiere a que podemos hacer ciertas operaciones con 2 dataframes que nos permitan unirlos o evaluar cosas en común. 

Los principales métodos para hacer esto son:

- `merge()`:
        El método `merge()` se utiliza para combinar dos DataFrames en función de una o más columnas que tengan valores comunes.
        Puedes especificar las columnas clave de combinación utilizando los parámetros left_on y right_on si las columnas tienen nombres diferentes en los DataFrames, o usar `left_index=True` y `right_index=True` si deseas combinar en función de los índices.
        El método `merge()` es más flexible y poderoso que `join()` y puede manejar casos más complejos de combinación de datos.

- `join()`:
        El método `join()` es similar a merge(), pero está diseñado para combinar DataFrames en función de sus índices.
        Por defecto, `join()` realiza una combinación de tipo "left join", donde las filas del DataFrame de la izquierda se conservan y se completan con valores correspondientes del DataFrame de la derecha.
        `join()` es conveniente cuando quieres combinar DataFrames en función de sus índices y cuando los DataFrames comparten los mismos nombres de columnas. Join se utiliza de manera diferente a `merge` ya que su sintaxis es del tipo `DataFrame.join(DataFrame2)`.

- `concatenate()`:
        La función `concatenate()` se utiliza para concatenar DataFrames a lo largo de un eje específico (por defecto, a lo largo del eje 0, es decir, las filas).
        Puedes especificar una lista de DataFrames que deseas concatenar y Pandas los combinará a lo largo del eje especificado.
        `concatenate()` es útil cuando deseas combinar múltiples DataFrames sin realizar una combinación basada en valores de columna o índice.

- `intersection()`:
        El método `intersection()` se utiliza para encontrar la intersección de los índices (o columnas) de dos DataFrames o Series.
        Puedes usar `intersection()` para encontrar los elementos que son comunes en los índices de los DataFrames.
        Esto es útil para identificar los elementos compartidos entre dos conjuntos de datos y puede ser útil al realizar operaciones de conjunto o al comparar datos.

En resumen, `merge()`, `join()`, `concatenate()` e `intersection()` son funciones y métodos fundamentales en Pandas que te permiten combinar, unir y manipular DataFrames y Series de manera eficiente y flexible. La elección de cuál utilizar depende de tus necesidades específicas y del tipo de operación que deseas realizar.

In [107]:
# Encontrar los productos que aparecen en ambos DataFrames
productos_en_comun = df_ventas.index.intersection(df_precios.index)

# Mostrar los productos en común
print("Productos en común:")
print(productos_en_comun)

Productos en común:
Index([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25],
      dtype='int64', name='ID')

In [108]:
# df_ventas y df_precios tienen el mismo índice 'ID' entonces podemos unirlos
df_combinado = pd.merge(df_ventas, df_precios, left_index=True, right_index=True)

# Mostrar el DataFrame combinado
df_combinado.head()

    Cantidad     Precio
ID
1         75  25.205015
2         73  82.690900
3         24   1.228061
4         54  25.953938
5         40  59.056260

---
<a name='ej-1'></a>
### **<font color="DodgerBlue">Ejercicio 2 - Índices </font>**

1. Utilice el método de join para unir los dataframes `df_ventas` y `df_precios` así como le hicimos con merge. Imprima el resultado.
2. Utilizando el objeto `df`, repita la operación de calcular el total de ventas como el producto de la columna "Ventas" con "Precio". Calcula la suma de este resultado y obtenga el total de ventas final. 
    
---

In [ ]:
#Paso 1
df_join=df_ventas.join(df_precios)
df_join.head()

In [ ]:
#Paso 2
df_join["Total_ventas"]=df_join["Cantidad"]*df_join["Precio"]
print(df_join.head())
print("Total de ventas final",df_join.Total_ventas.sum())

### **<font color="darkblue">  Transformaciones de Pandas </font>**

Las funciones `lambda` $\lambda$ y el método `apply()` son herramientas poderosas en Pandas para realizar operaciones personalizadas en DataFrames: 

- Una función lambda es una función anónima y pequeña que se define en una sola línea de código.

- Se utilizan comúnmente para definir funciones simples y de una sola expresión.

- Tienen una sintaxis básica:
````python
  lambda _argumentos_: expresión.
``````

- Las funciones lambda son útiles cuando necesitas una función rápida y temporal para realizar una tarea específica.

- Se pueden utilizar en combinación con muchas funciones de Python y de Pandas, como `map()`, `filter()`, `reduce()`, y también con el método `apply()` de Pandas.

#### <font color="orange"> **Ejemplo 1**

In [109]:
# Definir una función lambda para convertir pesos a euros (1 EURO = 20.30 MXN)
convertir_a_euros = lambda precio: precio * 1/20.30

# Aplicar la transformación a la columna 'Precio (MXM)' usando apply y la función lambda
df5['Precio (EUR)'] = df5['Precio'].apply(convertir_a_euros)
df5.head()

,ID,Nombre,Cantidad,Precio,Fecha,Precio (EUR)
Fecha,,,,,,
2026-09-09 21:25:23.478447,1,Producto 1,16,86.110440,2026-09-09 21:25:23.478447,4.241894
2026-09-08 21:25:23.478459,2,Producto 2,21,41.802614,2026-09-08 21:25:23.478459,2.059242
2026-09-07 21:25:23.478466,3,Producto 3,39,64.167494,2026-09-07 21:25:23.478466,3.160960
2026-09-06 21:25:23.478471,4,Producto 4,82,40.057213,2026-09-06 21:25:23.478471,1.973262
2026-09-05 21:25:23.478476,5,Producto 5,46,94.329607,2026-09-05 21:25:23.478476,4.646779

#### <font color="orange"> **Ejemplo 2**

In [110]:
# Definir una función lambda para convertir la cantidad de algo pero a docenas en enteros
cantidad_en_docenas = lambda cantidad: int(cantidad/12)

# Aplicar la transformación a la columna usando apply y la función lambda
df5['Docenas'] = df5['Cantidad'].apply(cantidad_en_docenas)
df5.head()

,ID,Nombre,Cantidad,Precio,Fecha,Precio (EUR),Docenas
Fecha,,,,,,,
2026-09-09 21:25:23.478447,1,Producto 1,16,86.110440,2026-09-09 21:25:23.478447,4.241894,1
2026-09-08 21:25:23.478459,2,Producto 2,21,41.802614,2026-09-08 21:25:23.478459,2.059242,1
2026-09-07 21:25:23.478466,3,Producto 3,39,64.167494,2026-09-07 21:25:23.478466,3.160960,3
2026-09-06 21:25:23.478471,4,Producto 4,82,40.057213,2026-09-06 21:25:23.478471,1.973262,6
2026-09-05 21:25:23.478476,5,Producto 5,46,94.329607,2026-09-05 21:25:23.478476,4.646779,3

**También podemos usar funciones pre-fabricadas para hacer transformaciones.**

In [111]:
def calcular_cuadrado(x):
    return x ** 2

df5['Precio al cuadrado'] = df5['Precio'].apply(calcular_cuadrado)
df5.head()

,ID,Nombre,Cantidad,Precio,Fecha,Precio (EUR),Docenas,Precio al cuadrado
Fecha,,,,,,,,
2026-09-09 21:25:23.478447,1,Producto 1,16,86.110440,2026-09-09 21:25:23.478447,4.241894,1,7415.007836
2026-09-08 21:25:23.478459,2,Producto 2,21,41.802614,2026-09-08 21:25:23.478459,2.059242,1,1747.458528
2026-09-07 21:25:23.478466,3,Producto 3,39,64.167494,2026-09-07 21:25:23.478466,3.160960,3,4117.467339
2026-09-06 21:25:23.478471,4,Producto 4,82,40.057213,2026-09-06 21:25:23.478471,1.973262,6,1604.580353
2026-09-05 21:25:23.478476,5,Producto 5,46,94.329607,2026-09-05 21:25:23.478476,4.646779,3,8898.074685

---

### **<font color="purple">Ejercicio 3 </font>**

Utilice el método lambdas para calcular el año en el que nacieron los individuos del primer df del notebook y guarde este resultado en la columna `Año de nacimiento`.

In [ ]:
df

In [ ]:
#Definiendo la operación
anio_nacimiento=lambda edad: 2026-edad

#Aplicando la función

anio=df.Edad.apply(anio_nacimiento)

#Agregando el resultado en una columna

df["anio_naci"]=anio

In [ ]:
df